name: test

on:
  workflow_call:
    inputs:
      mask-experimental:
        type: boolean
        default: true
        description: Always report experimental test as successful

permissions:
  contents: read

jobs:
  tests:
    name: >
      🖥️ ${{ matrix.os || 'Fedora' }} +
      ${{ !matrix.os && format('🛠️ {0} +', matrix.toolchain) || '' }}
      🐍 ${{ matrix.python-version }}
      ${{ matrix.experimental && '[🧪 Experimental]' || '' }}
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    container: ${{ !matrix.os && 'ghcr.io/lecrisut/dev-env:main' || '' }}
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      fail-fast: false
      matrix:
        toolchain: [ gcc, llvm, intel ]
        python-version: [ "3.8", "3.x" ]
        include:
          - os: macos-13
            toolchain: macos
            python-version: "3.x"
          - os: macos-latest
            toolchain: macos
            python-version: "3.x"
          - os: windows-2019
            toolchain: windows
            python-version: "3.x"
          - os: windows-latest
            toolchain: windows
            python-version: "3.x"
          - python-version: "3.x"
            toolchain: gcc
            experimental: true
            pre: true
    steps:
      - name: Enable msvc toolchain on windows
        uses: ilammy/msvc-dev-cmd@v1
        if: contains(matrix.os, 'windows')
      # Should be handled by defaults.shell: bash -l {0} and env.TOOLCHAIN: ${{ matrix.toolchain }}
      # But that approach does not seem to work with run-cmake :/
      - name: Activate Intel compilers
        run: |
          source /opt/intel/oneapi/setvars.sh
          printenv >> $GITHUB_ENV
          echo $PATH >> $GITHUB_PATH
        if: matrix.toolchain == 'intel'
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install pip-tools
          pip-compile --extra=test --strip-extras pyproject.toml ${{ matrix.pre && '--pre' }}
          python3 -m pip install -r requirements.txt
      - uses: lukka/get-cmake@latest
      - name: Run CMake configuration for ${{ matrix.toolchain }} toolchain
        # Cannot update passed v10.5 on Windows:
        # https://github.com/lukka/run-cmake/issues/142
        uses: lukka/run-cmake@v10.5
        with:
          workflowPreset: "${{ matrix.toolchain }}-ci"
        continue-on-error: ${{ matrix.experimental && inputs.mask-experimental}}
  cmake-version:
    name: >
      🔨 CMake ${{ matrix.cmake }}
      ${{ matrix.experimental && '[🧪 Experimental]' || '' }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      fail-fast: false
      matrix:
        cmake: [ "3.20", "latest", "latestrc" ]
        include:
          - cmake: latestrc
            experimental: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          python3 -m pip install pip-tools
          pip-compile --extra=test --strip-extras pyproject.toml ${{ matrix.pre && '--pre' }}
          python3 -m pip install -r requirements.txt
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: ${{ matrix.cmake }}
      - name: Run CMake workflow
        uses: lukka/run-cmake@v10
        with:
          workflowPreset: gcc-ci
        continue-on-error: ${{ matrix.experimental && inputs.mask-experimental}}
        if: matrix.cmake != '3.20'
      - name: Run CMake manually
        # Need CMake 3.25 to properly use the presets
        run: |
          cmake -B ./build -G Ninja \
            -DSPGLIB_WITH_Fortran=ON \
            -DSPGLIB_WITH_TESTS=ON \
            -DSPGLIB_WITH_Python=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_COMPILER=gcc \
            -DCMAKE_C_COMPILER=g++ \
            -DCMAKE_C_COMPILER=gfortran
          cmake --build ./build
          ctest --test-dir ./build -j $(nproc) --output-on-failure
        continue-on-error: ${{ matrix.experimental && inputs.mask-experimental}}
        if: matrix.cmake == '3.20'
  sanitizer:
    name: >
      🧹 ${{ matrix.sanitizer }} +
      🛠️ ${{ matrix.toolchain }}
    runs-on: ubuntu-latest
    container: ghcr.io/lecrisut/dev-env:main
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      fail-fast: false
      matrix:
        toolchain: [ gcc, llvm ]
        sanitizer: [ address ]
    env:
      SPGLIB_SANITIZER: ${{ matrix.sanitizer }}
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
      - name: Run CMake configuration for ${{ matrix.toolchain }} toolchain
        uses: lukka/run-cmake@v10
        with:
          workflowPreset: "${{ matrix.toolchain }}-ci-sanitizer"
